CREATE TABLE planeigenaar
(
  id serial NOT NULL,
  naam character varying(255),
  code character varying(255),
  CONSTRAINT planeigenaar_pkey PRIMARY KEY (id)
)
WITH (OIDS=FALSE);
insert into planeigenaar (naam, code) values ('Amsterdam', '0363');
insert into planeigenaar (naam, code) values ('Weesp', '0457');
insert into planeigenaar (naam, code) values ('Blaricum', '0376');
insert into planeigenaar (naam, code) values ('Ouder-Amstel', '0437');
insert into planeigenaar (naam, code) values ('Amstelveen', '0362');
insert into planeigenaar (naam, code) values ('Eemnes', '0317');
insert into planeigenaar (naam, code) values ('Laren', '0417');
insert into planeigenaar (naam, code) values ('Uithoorn', '0451');
insert into planeigenaar (naam, code) values ('Abcoude', '0305');
insert into planeigenaar (naam, code) values ('Bunschoten', '0313');
insert into planeigenaar (naam, code) values ('Hilversum', '0402');
insert into planeigenaar (naam, code) values ('De Ronde Venen', '0736');
insert into planeigenaar (naam, code) values ('Nieuwkoop', '0569');
insert into planeigenaar (naam, code) values ('Baarn', '0308');
insert into planeigenaar (naam, code) values ('Wijdemeren', '1696');
insert into planeigenaar (naam, code) values ('Loenen', '0329');
insert into planeigenaar (naam, code) values ('Nijkerk', '0267');
insert into planeigenaar (naam, code) values ('Soest', '0342');
insert into planeigenaar (naam, code) values ('Barneveld', '0203');
insert into planeigenaar (naam, code) values ('Breukelen', '0311');
insert into planeigenaar (naam, code) values ('Maarssen', '0333');
insert into planeigenaar (naam, code) values ('Amersfoort', '0307');
insert into planeigenaar (naam, code) values ('Leusden', '0327');
insert into planeigenaar (naam, code) values ('Utrecht', '0344');
insert into planeigenaar (naam, code) values ('De Bilt', '0310');
insert into planeigenaar (naam, code) values ('Renswoude', '0339');
insert into planeigenaar (naam, code) values ('Bodegraven', '0497');
insert into planeigenaar (naam, code) values ('Woudenberg', '0351');
insert into planeigenaar (naam, code) values ('Woerden', '0632');
insert into planeigenaar (naam, code) values ('Ede', '0228');
insert into planeigenaar (naam, code) values ('Scherpenzeel', '0279');
insert into planeigenaar (naam, code) values ('Utrechtse Heuvelrug', '1581');
insert into planeigenaar (naam, code) values ('Zeist', '0355');
insert into planeigenaar (naam, code) values ('Montfoort', '0335');
insert into planeigenaar (naam, code) values ('Oudewater', '0589');
insert into planeigenaar (naam, code) values ('Bunnik', '0312');
insert into planeigenaar (naam, code) values ('Reeuwijk', '0595');
insert into planeigenaar (naam, code) values ('Houten', '0321');
insert into planeigenaar (naam, code) values ('Veenendaal', '0345');
insert into planeigenaar (naam, code) values ('Nieuwegein', '0356');
insert into planeigenaar (naam, code) values ('IJsselstein', '0353');
insert into planeigenaar (naam, code) values ('Wijk bij Duurstede', '0352');
insert into planeigenaar (naam, code) values ('Vlist', '0623');
insert into planeigenaar (naam, code) values ('Rhenen', '0340');
insert into planeigenaar (naam, code) values ('Lopik', '0331');
insert into planeigenaar (naam, code) values ('Wageningen', '0289');
insert into planeigenaar (naam, code) values ('Vianen', '0620');
insert into planeigenaar (naam, code) values ('Culemborg', '0216');
insert into planeigenaar (naam, code) values ('Schoonhoven', '0608');
insert into planeigenaar (naam, code) values ('Liesveld', '0694');
insert into planeigenaar (naam, code) values ('Neder-Betuwe', '1740');
insert into planeigenaar (naam, code) values ('Leerdam', '0545');
insert into planeigenaar (naam, code) values ('Buren', '0214');
insert into planeigenaar (naam, code) values ('Zederik', '0707');
insert into planeigenaar (naam, code) values ('Arnhem', '0202');
insert into planeigenaar (naam, code) values ('Appingedam', '0003');
insert into planeigenaar (naam, code) values ('Bedum', '0005');
insert into planeigenaar (naam, code) values ('Bellingwedde', '0007');
insert into planeigenaar (naam, code) values ('Ten Boer', '0009');
insert into planeigenaar (naam, code) values ('Delfzijl', '0010');
insert into planeigenaar (naam, code) values ('Groningen', '0014');
insert into planeigenaar (naam, code) values ('Grootegast', '0015');
insert into planeigenaar (naam, code) values ('Haren', '0017');
insert into planeigenaar (naam, code) values ('Hoogezand-Sappemeer', '0018');
insert into planeigenaar (naam, code) values ('Leek', '0022');
insert into planeigenaar (naam, code) values ('Loppersum', '0024');
insert into planeigenaar (naam, code) values ('Marum', '0025');
insert into planeigenaar (naam, code) values ('Almere', '0034');
insert into planeigenaar (naam, code) values ('Stadskanaal', '0037');
insert into planeigenaar (naam, code) values ('Scheemda', '0039');
insert into planeigenaar (naam, code) values ('Slochteren', '0040');
insert into planeigenaar (naam, code) values ('Veendam', '0047');
insert into planeigenaar (naam, code) values ('Vlagtwedde', '0048');
insert into planeigenaar (naam, code) values ('Zeewolde', '0050');
insert into planeigenaar (naam, code) values ('Skarsterl?n', '0051');
insert into planeigenaar (naam, code) values ('Winschoten', '0052');
insert into planeigenaar (naam, code) values ('Winsum', '0053');
insert into planeigenaar (naam, code) values ('Boarnsterhim', '0055');
insert into planeigenaar (naam, code) values ('Zuidhorn', '0056');
insert into planeigenaar (naam, code) values ('Dongeradeel', '0058');
insert into planeigenaar (naam, code) values ('Achtkarspelen', '0059');
insert into planeigenaar (naam, code) values ('Ameland', '0060');
insert into planeigenaar (naam, code) values ('het Bildt', '0063');
insert into planeigenaar (naam, code) values ('Bolsward', '0064');
insert into planeigenaar (naam, code) values ('Dantumadeel', '0065');
insert into planeigenaar (naam, code) values ('Franekeradeel', '0070');
insert into planeigenaar (naam, code) values ('Harlingen', '0072');
insert into planeigenaar (naam, code) values ('Heerenveen', '0074');
insert into planeigenaar (naam, code) values ('Kollumerland en Nieuwkruisland', '0079');
insert into planeigenaar (naam, code) values ('Leeuwarden', '0080');
insert into planeigenaar (naam, code) values ('Leeuwarderadeel', '0081');
insert into planeigenaar (naam, code) values ('Lemsterland', '0082');
insert into planeigenaar (naam, code) values ('Menaldumadeel', '0083');
insert into planeigenaar (naam, code) values ('Ooststellingwerf', '0085');
insert into planeigenaar (naam, code) values ('Opsterland', '0086');
insert into planeigenaar (naam, code) values ('Schiermonnikoog', '0088');
insert into planeigenaar (naam, code) values ('Smallingerland', '0090');
insert into planeigenaar (naam, code) values ('Sneek', '0091');
insert into planeigenaar (naam, code) values ('Terschelling', '0093');
insert into planeigenaar (naam, code) values ('Vlieland', '0096');
insert into planeigenaar (naam, code) values ('Weststellingwerf', '0098');
insert into planeigenaar (naam, code) values ('Nijefurd', '0104');
insert into planeigenaar (naam, code) values ('Assen', '0106');
insert into planeigenaar (naam, code) values ('Coevorden', '0109');
insert into planeigenaar (naam, code) values ('Emmen', '0114');
insert into planeigenaar (naam, code) values ('Hoogeveen', '0118');
insert into planeigenaar (naam, code) values ('Meppel', '0119');
insert into planeigenaar (naam, code) values ('Littenseradiel', '0140');
insert into planeigenaar (naam, code) values ('Almelo', '0141');
insert into planeigenaar (naam, code) values ('Borne', '0147');
insert into planeigenaar (naam, code) values ('Dalfsen', '0148');
insert into planeigenaar (naam, code) values ('Deventer', '0150');
insert into planeigenaar (naam, code) values ('Enschede', '0153');
insert into planeigenaar (naam, code) values ('Haaksbergen', '0158');
insert into planeigenaar (naam, code) values ('Hardenberg', '0160');
insert into planeigenaar (naam, code) values ('Hellendoorn', '0163');
insert into planeigenaar (naam, code) values ('Hengelo', '0164');
insert into planeigenaar (naam, code) values ('Kampen', '0166');
insert into planeigenaar (naam, code) values ('Losser', '0168');
insert into planeigenaar (naam, code) values ('Noordoostpolder', '0171');
insert into planeigenaar (naam, code) values ('Oldenzaal', '0173');
insert into planeigenaar (naam, code) values ('Ommen', '0175');
insert into planeigenaar (naam, code) values ('Raalte', '0177');
insert into planeigenaar (naam, code) values ('Staphorst', '0180');
insert into planeigenaar (naam, code) values ('Tubbergen', '0183');
insert into planeigenaar (naam, code) values ('Urk', '0184');
insert into planeigenaar (naam, code) values ('Wierden', '0189');
insert into planeigenaar (naam, code) values ('Zwolle', '0193');
insert into planeigenaar (naam, code) values ('Rijnwaarden', '0196');
insert into planeigenaar (naam, code) values ('Aalten', '0197');
insert into planeigenaar (naam, code) values ('Apeldoorn', '0200');
insert into planeigenaar (naam, code) values ('Arnhem', '0202');
insert into planeigenaar (naam, code) values ('Barneveld', '0203');
insert into planeigenaar (naam, code) values ('Beuningen', '0209');
insert into planeigenaar (naam, code) values ('Brummen', '0213');
insert into planeigenaar (naam, code) values ('Buren', '0214');
insert into planeigenaar (naam, code) values ('Culemborg', '0216');
insert into planeigenaar (naam, code) values ('Doesburg', '0221');
insert into planeigenaar (naam, code) values ('Doetinchem', '0222');
insert into planeigenaar (naam, code) values ('Druten', '0225');
insert into planeigenaar (naam, code) values ('Duiven', '0226');
insert into planeigenaar (naam, code) values ('Ede', '0228');
insert into planeigenaar (naam, code) values ('Elburg', '0230');
insert into planeigenaar (naam, code) values ('Epe', '0232');
insert into planeigenaar (naam, code) values ('Ermelo', '0233');
insert into planeigenaar (naam, code) values ('Geldermalsen', '0236');
insert into planeigenaar (naam, code) values ('Groesbeek', '0241');
insert into planeigenaar (naam, code) values ('Harderwijk', '0243');
insert into planeigenaar (naam, code) values ('Hattem', '0244');
insert into planeigenaar (naam, code) values ('Heerde', '0246');
insert into planeigenaar (naam, code) values ('Heumen', '0252');
insert into planeigenaar (naam, code) values ('Lochem', '0262');
insert into planeigenaar (naam, code) values ('Maasdriel', '0263');
insert into planeigenaar (naam, code) values ('Millingen aan de Rijn', '0265');
insert into planeigenaar (naam, code) values ('Nijkerk', '0267');
insert into planeigenaar (naam, code) values ('Nijmegen', '0268');
insert into planeigenaar (naam, code) values ('Oldebroek', '0269');
insert into planeigenaar (naam, code) values ('Putten', '0273');
insert into planeigenaar (naam, code) values ('Renkum', '0274');
insert into planeigenaar (naam, code) values ('Rheden', '0275');
insert into planeigenaar (naam, code) values ('Rozendaal', '0277');
insert into planeigenaar (naam, code) values ('Scherpenzeel', '0279');
insert into planeigenaar (naam, code) values ('Tiel', '0281');
insert into planeigenaar (naam, code) values ('Ubbergen', '0282');
insert into planeigenaar (naam, code) values ('Voorst', '0285');
insert into planeigenaar (naam, code) values ('Wageningen', '0289');
insert into planeigenaar (naam, code) values ('Westervoort', '0293');
insert into planeigenaar (naam, code) values ('Winterswijk', '0294');
insert into planeigenaar (naam, code) values ('Wijchen', '0296');
insert into planeigenaar (naam, code) values ('Zaltbommel', '0297');
insert into planeigenaar (naam, code) values ('Zevenaar', '0299');
insert into planeigenaar (naam, code) values ('Zutphen', '0301');
insert into planeigenaar (naam, code) values ('Nunspeet', '0302');
insert into planeigenaar (naam, code) values ('Dronten', '0303');
insert into planeigenaar (naam, code) values ('Neerijnen', '0304');
insert into planeigenaar (naam, code) values ('Abcoude', '0305');
insert into planeigenaar (naam, code) values ('Amersfoort', '0307');
insert into planeigenaar (naam, code) values ('Baarn', '0308');
insert into planeigenaar (naam, code) values ('De Bilt', '0310');
insert into planeigenaar (naam, code) values ('Breukelen', '0311');
insert into planeigenaar (naam, code) values ('Bunnik', '0312');
insert into planeigenaar (naam, code) values ('Bunschoten', '0313');
insert into planeigenaar (naam, code) values ('Eemnes', '0317');
insert into planeigenaar (naam, code) values ('Houten', '0321');
insert into planeigenaar (naam, code) values ('Leusden', '0327');
insert into planeigenaar (naam, code) values ('Loenen', '0329');
insert into planeigenaar (naam, code) values ('Lopik', '0331');
insert into planeigenaar (naam, code) values ('Maarssen', '0333');
insert into planeigenaar (naam, code) values ('Montfoort', '0335');
insert into planeigenaar (naam, code) values ('Renswoude', '0339');
insert into planeigenaar (naam, code) values ('Rhenen', '0340');
insert into planeigenaar (naam, code) values ('Soest', '0342');
insert into planeigenaar (naam, code) values ('Utrecht', '0344');
insert into planeigenaar (naam, code) values ('Veenendaal', '0345');
insert into planeigenaar (naam, code) values ('Woudenberg', '0351');
insert into planeigenaar (naam, code) values ('Wijk bij Duurstede', '0352');
insert into planeigenaar (naam, code) values ('IJsselstein', '0353');
insert into planeigenaar (naam, code) values ('Zeist', '0355');
insert into planeigenaar (naam, code) values ('Nieuwegein', '0356');
insert into planeigenaar (naam, code) values ('Aalsmeer', '0358');
insert into planeigenaar (naam, code) values ('Alkmaar', '0361');
insert into planeigenaar (naam, code) values ('Amstelveen', '0362');
insert into planeigenaar (naam, code) values ('Amsterdam', '0363');
insert into planeigenaar (naam, code) values ('Andijk', '0364');
insert into planeigenaar (naam, code) values ('Graft-De Rijp', '0365');
insert into planeigenaar (naam, code) values ('Anna Paulowna', '0366');
insert into planeigenaar (naam, code) values ('Beemster', '0370');
insert into planeigenaar (naam, code) values ('Bennebroek', '0372');
insert into planeigenaar (naam, code) values ('Bergen (NH.)', '0373');
insert into planeigenaar (naam, code) values ('Beverwijk', '0375');
insert into planeigenaar (naam, code) values ('Blaricum', '0376');
insert into planeigenaar (naam, code) values ('Bloemendaal', '0377');
insert into planeigenaar (naam, code) values ('Bussum', '0381');
insert into planeigenaar (naam, code) values ('Castricum', '0383');
insert into planeigenaar (naam, code) values ('Diemen', '0384');
insert into planeigenaar (naam, code) values ('Edam-Volendam', '0385');
insert into planeigenaar (naam, code) values ('Enkhuizen', '0388');
insert into planeigenaar (naam, code) values ('Haarlem', '0392');
insert into planeigenaar (naam, code) values ('Haarlemmerliede en Spaarnwoude', '0393');
insert into planeigenaar (naam, code) values ('Haarlemmermeer', '0394');
insert into planeigenaar (naam, code) values ('Harenkarspel', '0395');
insert into planeigenaar (naam, code) values ('Heemskerk', '0396');
insert into planeigenaar (naam, code) values ('Heemstede', '0397');
insert into planeigenaar (naam, code) values ('Heerhugowaard', '0398');
insert into planeigenaar (naam, code) values ('Heiloo', '0399');
insert into planeigenaar (naam, code) values ('Den Helder', '0400');
insert into planeigenaar (naam, code) values ('Hilversum', '0402');
insert into planeigenaar (naam, code) values ('Hoorn', '0405');
insert into planeigenaar (naam, code) values ('Huizen', '0406');
insert into planeigenaar (naam, code) values ('Niedorp', '0412');
insert into planeigenaar (naam, code) values ('Landsmeer', '0415');
insert into planeigenaar (naam, code) values ('Langedijk', '0416');
insert into planeigenaar (naam, code) values ('Laren', '0417');
insert into planeigenaar (naam, code) values ('Medemblik', '0420');
insert into planeigenaar (naam, code) values ('Muiden', '0424');
insert into planeigenaar (naam, code) values ('Naarden', '0425');
insert into planeigenaar (naam, code) values ('Oostzaan', '0431');
insert into planeigenaar (naam, code) values ('Opmeer', '0432');
insert into planeigenaar (naam, code) values ('Ouder-Amstel', '0437');
insert into planeigenaar (naam, code) values ('Purmerend', '0439');
insert into planeigenaar (naam, code) values ('Schagen', '0441');
insert into planeigenaar (naam, code) values ('Texel', '0448');
insert into planeigenaar (naam, code) values ('Uitgeest', '0450');
insert into planeigenaar (naam, code) values ('Uithoorn', '0451');
insert into planeigenaar (naam, code) values ('Velsen', '0453');
insert into planeigenaar (naam, code) values ('Weesp', '0457');
insert into planeigenaar (naam, code) values ('Schermer', '0458');
insert into planeigenaar (naam, code) values ('Wervershoof', '0459');
insert into planeigenaar (naam, code) values ('Wieringen', '0462');
insert into planeigenaar (naam, code) values ('Wieringermeer', '0463');
insert into planeigenaar (naam, code) values ('Zandvoort', '0473');
insert into planeigenaar (naam, code) values ('Zijpe', '0476');
insert into planeigenaar (naam, code) values ('Zeevang', '0478');
insert into planeigenaar (naam, code) values ('Zaanstad', '0479');
insert into planeigenaar (naam, code) values ('Alblasserdam', '0482');
insert into planeigenaar (naam, code) values ('Alkemade', '0483');
insert into planeigenaar (naam, code) values ('Alphen aan den Rijn', '0484');
insert into planeigenaar (naam, code) values ('Barendrecht', '0489');
insert into planeigenaar (naam, code) values ('Bergambacht', '0491');
insert into planeigenaar (naam, code) values ('Bodegraven', '0497');
insert into planeigenaar (naam, code) values ('Drechterland', '0498');
insert into planeigenaar (naam, code) values ('Boskoop', '0499');
insert into planeigenaar (naam, code) values ('Brielle', '0501');
insert into planeigenaar (naam, code) values ('Capelle aan den IJssel', '0502');
insert into planeigenaar (naam, code) values ('Delft', '0503');
insert into planeigenaar (naam, code) values ('Dirksland', '0504');
insert into planeigenaar (naam, code) values ('Dordrecht', '0505');
insert into planeigenaar (naam, code) values ('Goedereede', '0511');
insert into planeigenaar (naam, code) values ('Gorinchem', '0512');
insert into planeigenaar (naam, code) values ('Gouda', '0513');
insert into planeigenaar (naam, code) values ('''s-Gravenhage', '0518');
insert into planeigenaar (naam, code) values ('Hardinxveld-Giessendam', '0523');
insert into planeigenaar (naam, code) values ('Hellevoetsluis', '0530');
insert into planeigenaar (naam, code) values ('Hendrik-Ido-Ambacht', '0531');
insert into planeigenaar (naam, code) values ('Stede Broec', '0532');
insert into planeigenaar (naam, code) values ('Hillegom', '0534');
insert into planeigenaar (naam, code) values ('Katwijk', '0537');
insert into planeigenaar (naam, code) values ('Krimpen aan den IJssel', '0542');
insert into planeigenaar (naam, code) values ('Leerdam', '0545');
insert into planeigenaar (naam, code) values ('Leiden', '0546');
insert into planeigenaar (naam, code) values ('Leiderdorp', '0547');
insert into planeigenaar (naam, code) values ('Lisse', '0553');
insert into planeigenaar (naam, code) values ('Maassluis', '0556');
insert into planeigenaar (naam, code) values ('Middelharnis', '0559');
insert into planeigenaar (naam, code) values ('Moordrecht', '0563');
insert into planeigenaar (naam, code) values ('Nieuwerkerk aan den IJssel', '0567');
insert into planeigenaar (naam, code) values ('Bernisse', '0568');
insert into planeigenaar (naam, code) values ('Nieuwkoop', '0569');
insert into planeigenaar (naam, code) values ('Nieuw-Lekkerland', '0571');
insert into planeigenaar (naam, code) values ('Noordwijk', '0575');
insert into planeigenaar (naam, code) values ('Noordwijkerhout', '0576');
insert into planeigenaar (naam, code) values ('Oegstgeest', '0579');
insert into planeigenaar (naam, code) values ('Oostflakkee', '0580');
insert into planeigenaar (naam, code) values ('Oud-Beijerland', '0584');
insert into planeigenaar (naam, code) values ('Binnenmaas', '0585');
insert into planeigenaar (naam, code) values ('Korendijk', '0588');
insert into planeigenaar (naam, code) values ('Oudewater', '0589');
insert into planeigenaar (naam, code) values ('Papendrecht', '0590');
insert into planeigenaar (naam, code) values ('Reeuwijk', '0595');
insert into planeigenaar (naam, code) values ('Ridderkerk', '0597');
insert into planeigenaar (naam, code) values ('Rotterdam', '0599');
insert into planeigenaar (naam, code) values ('Rozenburg', '0600');
insert into planeigenaar (naam, code) values ('Rijswijk', '0603');
insert into planeigenaar (naam, code) values ('Schiedam', '0606');
insert into planeigenaar (naam, code) values ('Schoonhoven', '0608');
insert into planeigenaar (naam, code) values ('Sliedrecht', '0610');
insert into planeigenaar (naam, code) values ('Cromstrijen', '0611');
insert into planeigenaar (naam, code) values ('Spijkenisse', '0612');
insert into planeigenaar (naam, code) values ('Albrandswaard', '0613');
insert into planeigenaar (naam, code) values ('Westvoorne', '0614');
insert into planeigenaar (naam, code) values ('Strijen', '0617');
insert into planeigenaar (naam, code) values ('Vianen', '0620');
insert into planeigenaar (naam, code) values ('Vlaardingen', '0622');
insert into planeigenaar (naam, code) values ('Vlist', '0623');
insert into planeigenaar (naam, code) values ('Voorschoten', '0626');
insert into planeigenaar (naam, code) values ('Waddinxveen', '0627');
insert into planeigenaar (naam, code) values ('Wassenaar', '0629');
insert into planeigenaar (naam, code) values ('Woerden', '0632');
insert into planeigenaar (naam, code) values ('Zoetermeer', '0637');
insert into planeigenaar (naam, code) values ('Zoeterwoude', '0638');
insert into planeigenaar (naam, code) values ('Zwijndrecht', '0642');
insert into planeigenaar (naam, code) values ('Nederlek', '0643');
insert into planeigenaar (naam, code) values ('Ouderkerk', '0644');
insert into planeigenaar (naam, code) values ('Jacobswoude', '0645');
insert into planeigenaar (naam, code) values ('Gaasterl?n-Sleat', '0653');
insert into planeigenaar (naam, code) values ('Borsele', '0654');
insert into planeigenaar (naam, code) values ('Goes', '0664');
insert into planeigenaar (naam, code) values ('West Maas en Waal', '0668');
insert into planeigenaar (naam, code) values ('Hulst', '0677');
insert into planeigenaar (naam, code) values ('Kapelle', '0678');
insert into planeigenaar (naam, code) values ('Wymbritseradiel', '0683');
insert into planeigenaar (naam, code) values ('Middelburg', '0687');
insert into planeigenaar (naam, code) values ('Giessenlanden', '0689');
insert into planeigenaar (naam, code) values ('Graafstroom', '0693');
insert into planeigenaar (naam, code) values ('Liesveld', '0694');
insert into planeigenaar (naam, code) values ('Reimerswaal', '0703');
insert into planeigenaar (naam, code) values ('Zederik', '0707');
insert into planeigenaar (naam, code) values ('W?nseradiel', '0710');
insert into planeigenaar (naam, code) values ('Terneuzen', '0715');
insert into planeigenaar (naam, code) values ('Tholen', '0716');
insert into planeigenaar (naam, code) values ('Veere', '0717');
insert into planeigenaar (naam, code) values ('Vlissingen', '0718');
insert into planeigenaar (naam, code) values ('Lingewaal', '0733');
insert into planeigenaar (naam, code) values ('De Ronde Venen', '0736');
insert into planeigenaar (naam, code) values ('Tytsjerksteradiel', '0737');
insert into planeigenaar (naam, code) values ('Aalburg', '0738');
insert into planeigenaar (naam, code) values ('Asten', '0743');
insert into planeigenaar (naam, code) values ('Baarle-Nassau', '0744');
insert into planeigenaar (naam, code) values ('Bergen op Zoom', '0748');
insert into planeigenaar (naam, code) values ('Best', '0753');
insert into planeigenaar (naam, code) values ('Boekel', '0755');
insert into planeigenaar (naam, code) values ('Boxmeer', '0756');
insert into planeigenaar (naam, code) values ('Boxtel', '0757');
insert into planeigenaar (naam, code) values ('Breda', '0758');
insert into planeigenaar (naam, code) values ('Deurne', '0762');
insert into planeigenaar (naam, code) values ('Pekela', '0765');
insert into planeigenaar (naam, code) values ('Dongen', '0766');
insert into planeigenaar (naam, code) values ('Eersel', '0770');
insert into planeigenaar (naam, code) values ('Eindhoven', '0772');
insert into planeigenaar (naam, code) values ('Etten-Leur', '0777');
insert into planeigenaar (naam, code) values ('Geertruidenberg', '0779');
insert into planeigenaar (naam, code) values ('Gilze en Rijen', '0784');
insert into planeigenaar (naam, code) values ('Goirle', '0785');
insert into planeigenaar (naam, code) values ('Grave', '0786');
insert into planeigenaar (naam, code) values ('Haaren', '0788');
insert into planeigenaar (naam, code) values ('Helmond', '0794');
insert into planeigenaar (naam, code) values ('''s-Hertogenbosch', '0796');
insert into planeigenaar (naam, code) values ('Heusden', '0797');
insert into planeigenaar (naam, code) values ('Hilvarenbeek', '0798');
insert into planeigenaar (naam, code) values ('Lith', '0808');
insert into planeigenaar (naam, code) values ('Loon op Zand', '0809');
insert into planeigenaar (naam, code) values ('Mill en Sint Hubert', '0815');
insert into planeigenaar (naam, code) values ('Nuenen, Gerwen en Nederwetten', '0820');
insert into planeigenaar (naam, code) values ('Oirschot', '0823');
insert into planeigenaar (naam, code) values ('Oisterwijk', '0824');
insert into planeigenaar (naam, code) values ('Oosterhout', '0826');
insert into planeigenaar (naam, code) values ('Oss', '0828');
insert into planeigenaar (naam, code) values ('Rucphen', '0840');
insert into planeigenaar (naam, code) values ('Schijndel', '0844');
insert into planeigenaar (naam, code) values ('Sint-Michielsgestel', '0845');
insert into planeigenaar (naam, code) values ('Sint-Oedenrode', '0846');
insert into planeigenaar (naam, code) values ('Someren', '0847');
insert into planeigenaar (naam, code) values ('Son en Breugel', '0848');
insert into planeigenaar (naam, code) values ('Steenbergen', '0851');
insert into planeigenaar (naam, code) values ('Waterland', '0852');
insert into planeigenaar (naam, code) values ('Tilburg', '0855');
insert into planeigenaar (naam, code) values ('Uden', '0856');
insert into planeigenaar (naam, code) values ('Valkenswaard', '0858');
insert into planeigenaar (naam, code) values ('Veghel', '0860');
insert into planeigenaar (naam, code) values ('Veldhoven', '0861');
insert into planeigenaar (naam, code) values ('Vught', '0865');
insert into planeigenaar (naam, code) values ('Waalre', '0866');
insert into planeigenaar (naam, code) values ('Waalwijk', '0867');
insert into planeigenaar (naam, code) values ('Werkendam', '0870');
insert into planeigenaar (naam, code) values ('Woensdrecht', '0873');
insert into planeigenaar (naam, code) values ('Woudrichem', '0874');
insert into planeigenaar (naam, code) values ('Zundert', '0879');
insert into planeigenaar (naam, code) values ('Wormerland', '0880');
insert into planeigenaar (naam, code) values ('Onderbanken', '0881');
insert into planeigenaar (naam, code) values ('Landgraaf', '0882');
insert into planeigenaar (naam, code) values ('Arcen en Velden', '0885');
insert into planeigenaar (naam, code) values ('Beek', '0888');
insert into planeigenaar (naam, code) values ('Beesel', '0889');
insert into planeigenaar (naam, code) values ('Bergen (L.)', '0893');
insert into planeigenaar (naam, code) values ('Brunssum', '0899');
insert into planeigenaar (naam, code) values ('Eijsden', '0905');
insert into planeigenaar (naam, code) values ('Gennep', '0907');
insert into planeigenaar (naam, code) values ('Heerlen', '0917');
insert into planeigenaar (naam, code) values ('Helden', '0918');
insert into planeigenaar (naam, code) values ('Kerkrade', '0928');
insert into planeigenaar (naam, code) values ('Kessel', '0929');
insert into planeigenaar (naam, code) values ('Maasbree', '0934');
insert into planeigenaar (naam, code) values ('Maastricht', '0935');
insert into planeigenaar (naam, code) values ('Margraten', '0936');
insert into planeigenaar (naam, code) values ('Meerssen', '0938');
insert into planeigenaar (naam, code) values ('Meijel', '0941');
insert into planeigenaar (naam, code) values ('Mook en Middelaar', '0944');
insert into planeigenaar (naam, code) values ('Nederweert', '0946');
insert into planeigenaar (naam, code) values ('Nuth', '0951');
insert into planeigenaar (naam, code) values ('Roermond', '0957');
insert into planeigenaar (naam, code) values ('Schinnen', '0962');
insert into planeigenaar (naam, code) values ('Sevenum', '0964');
insert into planeigenaar (naam, code) values ('Simpelveld', '0965');
insert into planeigenaar (naam, code) values ('Stein', '0971');
insert into planeigenaar (naam, code) values ('Vaals', '0981');
insert into planeigenaar (naam, code) values ('Venlo', '0983');
insert into planeigenaar (naam, code) values ('Venray', '0984');
insert into planeigenaar (naam, code) values ('Voerendaal', '0986');
insert into planeigenaar (naam, code) values ('Weert', '0988');
insert into planeigenaar (naam, code) values ('Meerlo-Wanssum', '0993');
insert into planeigenaar (naam, code) values ('Valkenburg aan de Geul', '0994');
insert into planeigenaar (naam, code) values ('Lelystad', '0995');
insert into planeigenaar (naam, code) values ('Horst aan de Maas', '1507');
insert into planeigenaar (naam, code) values ('Oude IJsselstreek', '1509');
insert into planeigenaar (naam, code) values ('Teylingen', '1525');
insert into planeigenaar (naam, code) values ('Utrechtse Heuvelrug', '1581');
insert into planeigenaar (naam, code) values ('Oost Gelre', '1586');
insert into planeigenaar (naam, code) values ('Koggenland', '1598');
insert into planeigenaar (naam, code) values ('Lansingerland', '1621');
insert into planeigenaar (naam, code) values ('Leudal', '1640');
insert into planeigenaar (naam, code) values ('Maasgouw', '1641');
insert into planeigenaar (naam, code) values ('Eemsmond', '1651');
insert into planeigenaar (naam, code) values ('Gemert-Bakel', '1652');
insert into planeigenaar (naam, code) values ('Halderberge', '1655');
insert into planeigenaar (naam, code) values ('Heeze-Leende', '1658');
insert into planeigenaar (naam, code) values ('Laarbeek', '1659');
insert into planeigenaar (naam, code) values ('Reiderland', '1661');
insert into planeigenaar (naam, code) values ('De Marne', '1663');
insert into planeigenaar (naam, code) values ('Zevenhuizen-Moerkapelle', '1666');
insert into planeigenaar (naam, code) values ('Reusel-De Mierden', '1667');
insert into planeigenaar (naam, code) values ('Roerdalen', '1669');
insert into planeigenaar (naam, code) values ('Maasdonk', '1671');
insert into planeigenaar (naam, code) values ('Rijnwoude', '1672');
insert into planeigenaar (naam, code) values ('Roosendaal', '1674');
insert into planeigenaar (naam, code) values ('Schouwen-Duiveland', '1676');
insert into planeigenaar (naam, code) values ('Aa en Hunze', '1680');
insert into planeigenaar (naam, code) values ('Borger-Odoorn', '1681');
insert into planeigenaar (naam, code) values ('Cuijk', '1684');
insert into planeigenaar (naam, code) values ('Landerd', '1685');
insert into planeigenaar (naam, code) values ('De Wolden', '1690');
insert into planeigenaar (naam, code) values ('Noord-Beveland', '1695');
insert into planeigenaar (naam, code) values ('Wijdemeren', '1696');
insert into planeigenaar (naam, code) values ('Noordenveld', '1699');
insert into planeigenaar (naam, code) values ('Twenterand', '1700');
insert into planeigenaar (naam, code) values ('Westerveld', '1701');
insert into planeigenaar (naam, code) values ('Sint Anthonis', '1702');
insert into planeigenaar (naam, code) values ('Lingewaard', '1705');
insert into planeigenaar (naam, code) values ('Cranendonck', '1706');
insert into planeigenaar (naam, code) values ('Steenwijkerland', '1708');
insert into planeigenaar (naam, code) values ('Moerdijk', '1709');
insert into planeigenaar (naam, code) values ('Echt-Susteren', '1711');
insert into planeigenaar (naam, code) values ('Sluis', '1714');
insert into planeigenaar (naam, code) values ('Drimmelen', '1719');
insert into planeigenaar (naam, code) values ('Bernheze', '1721');
insert into planeigenaar (naam, code) values ('Ferwerderadiel', '1722');
insert into planeigenaar (naam, code) values ('Alphen-Chaam', '1723');
insert into planeigenaar (naam, code) values ('Bergeijk', '1724');
insert into planeigenaar (naam, code) values ('Bladel', '1728');
insert into planeigenaar (naam, code) values ('Gulpen-Wittem', '1729');
insert into planeigenaar (naam, code) values ('Tynaarlo', '1730');
insert into planeigenaar (naam, code) values ('Midden-Drenthe', '1731');
insert into planeigenaar (naam, code) values ('Overbetuwe', '1734');
insert into planeigenaar (naam, code) values ('Hof van Twente', '1735');
insert into planeigenaar (naam, code) values ('Neder-Betuwe', '1740');
insert into planeigenaar (naam, code) values ('Rijssen-Holten', '1742');
insert into planeigenaar (naam, code) values ('Geldrop-Mierlo', '1771');
insert into planeigenaar (naam, code) values ('Olst-Wijhe', '1773');
insert into planeigenaar (naam, code) values ('Dinkelland', '1774');
insert into planeigenaar (naam, code) values ('Westland', '1783');
insert into planeigenaar (naam, code) values ('Midden-Delfland', '1842');
insert into planeigenaar (naam, code) values ('Berkelland', '1859');
insert into planeigenaar (naam, code) values ('Bronckhorst', '1876');
insert into planeigenaar (naam, code) values ('Sittard-Geleen', '1883');
insert into planeigenaar (naam, code) values ('Zwartewaterland', '1896');
insert into planeigenaar (naam, code) values ('Leidschendam-Voorburg', '1916');
insert into planeigenaar (naam, code) values ('Pijnacker-Nootdorp', '1926');
insert into planeigenaar (naam, code) values ('Montferland', '1955');
insert into planeigenaar (naam, code) values ('Menterwolde', '1987');
