CREATE TABLE planeigenaar
(
id number(10,0) NOT NULL,
naam varchar2(255 char),
code varchar2(255 char),
PRIMARY KEY (id)
);

create sequence planeigenaar_id_seq;

insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Amsterdam', '0363');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Weesp', '0457');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Blaricum', '0376');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ouder-Amstel', '0437');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Amstelveen', '0362');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Eemnes', '0317');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Laren', '0417');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Uithoorn', '0451');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Abcoude', '0305');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bunschoten', '0313');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hilversum', '0402');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'De Ronde Venen', '0736');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nieuwkoop', '0569');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Baarn', '0308');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wijdemeren', '1696');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Loenen', '0329');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nijkerk', '0267');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Soest', '0342');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Barneveld', '0203');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Breukelen', '0311');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Maarssen', '0333');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Amersfoort', '0307');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Leusden', '0327');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Utrecht', '0344');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'De Bilt', '0310');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Renswoude', '0339');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bodegraven', '0497');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Woudenberg', '0351');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Woerden', '0632');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ede', '0228');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Scherpenzeel', '0279');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Utrechtse Heuvelrug', '1581');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zeist', '0355');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Montfoort', '0335');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oudewater', '0589');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bunnik', '0312');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Reeuwijk', '0595');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Houten', '0321');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Veenendaal', '0345');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nieuwegein', '0356');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'IJsselstein', '0353');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wijk bij Duurstede', '0352');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Vlist', '0623');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Rhenen', '0340');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Lopik', '0331');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wageningen', '0289');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Vianen', '0620');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Culemborg', '0216');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Schoonhoven', '0608');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Liesveld', '0694');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Neder-Betuwe', '1740');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Leerdam', '0545');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Buren', '0214');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zederik', '0707');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Arnhem', '0202');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Appingedam', '0003');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bedum', '0005');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bellingwedde', '0007');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ten Boer', '0009');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Delfzijl', '0010');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Groningen', '0014');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Grootegast', '0015');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Haren', '0017');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hoogezand-Sappemeer', '0018');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Leek', '0022');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Loppersum', '0024');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Marum', '0025');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Almere', '0034');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Stadskanaal', '0037');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Scheemda', '0039');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Slochteren', '0040');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Veendam', '0047');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Vlagtwedde', '0048');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zeewolde', '0050');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Skarsterl?n', '0051');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Winschoten', '0052');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Winsum', '0053');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Boarnsterhim', '0055');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zuidhorn', '0056');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Dongeradeel', '0058');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Achtkarspelen', '0059');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ameland', '0060');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'het Bildt', '0063');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bolsward', '0064');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Dantumadeel', '0065');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Franekeradeel', '0070');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Harlingen', '0072');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Heerenveen', '0074');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Kollumerland en Nieuwkruisland', '0079');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Leeuwarden', '0080');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Leeuwarderadeel', '0081');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Lemsterland', '0082');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Menaldumadeel', '0083');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ooststellingwerf', '0085');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Opsterland', '0086');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Schiermonnikoog', '0088');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Smallingerland', '0090');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Sneek', '0091');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Terschelling', '0093');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Vlieland', '0096');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Weststellingwerf', '0098');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nijefurd', '0104');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Assen', '0106');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Coevorden', '0109');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Emmen', '0114');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hoogeveen', '0118');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Meppel', '0119');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Littenseradiel', '0140');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Almelo', '0141');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Borne', '0147');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Dalfsen', '0148');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Deventer', '0150');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Enschede', '0153');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Haaksbergen', '0158');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hardenberg', '0160');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hellendoorn', '0163');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hengelo', '0164');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Kampen', '0166');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Losser', '0168');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Noordoostpolder', '0171');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oldenzaal', '0173');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ommen', '0175');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Raalte', '0177');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Staphorst', '0180');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Tubbergen', '0183');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Urk', '0184');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wierden', '0189');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zwolle', '0193');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Rijnwaarden', '0196');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Aalten', '0197');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Apeldoorn', '0200');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Arnhem', '0202');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Barneveld', '0203');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Beuningen', '0209');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Brummen', '0213');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Buren', '0214');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Culemborg', '0216');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Doesburg', '0221');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Doetinchem', '0222');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Druten', '0225');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Duiven', '0226');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ede', '0228');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Elburg', '0230');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Epe', '0232');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ermelo', '0233');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Geldermalsen', '0236');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Groesbeek', '0241');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Harderwijk', '0243');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hattem', '0244');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Heerde', '0246');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Heumen', '0252');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Lochem', '0262');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Maasdriel', '0263');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Millingen aan de Rijn', '0265');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nijkerk', '0267');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nijmegen', '0268');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oldebroek', '0269');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Putten', '0273');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Renkum', '0274');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Rheden', '0275');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Rozendaal', '0277');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Scherpenzeel', '0279');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Tiel', '0281');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ubbergen', '0282');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Voorst', '0285');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wageningen', '0289');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Westervoort', '0293');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Winterswijk', '0294');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wijchen', '0296');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zaltbommel', '0297');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zevenaar', '0299');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zutphen', '0301');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nunspeet', '0302');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Dronten', '0303');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Neerijnen', '0304');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Abcoude', '0305');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Amersfoort', '0307');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Baarn', '0308');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'De Bilt', '0310');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Breukelen', '0311');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bunnik', '0312');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bunschoten', '0313');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Eemnes', '0317');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Houten', '0321');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Leusden', '0327');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Loenen', '0329');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Lopik', '0331');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Maarssen', '0333');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Montfoort', '0335');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Renswoude', '0339');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Rhenen', '0340');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Soest', '0342');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Utrecht', '0344');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Veenendaal', '0345');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Woudenberg', '0351');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wijk bij Duurstede', '0352');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'IJsselstein', '0353');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zeist', '0355');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nieuwegein', '0356');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Aalsmeer', '0358');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Alkmaar', '0361');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Amstelveen', '0362');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Amsterdam', '0363');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Andijk', '0364');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Graft-De Rijp', '0365');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Anna Paulowna', '0366');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Beemster', '0370');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bennebroek', '0372');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bergen (NH.)', '0373');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Beverwijk', '0375');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Blaricum', '0376');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bloemendaal', '0377');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bussum', '0381');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Castricum', '0383');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Diemen', '0384');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Edam-Volendam', '0385');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Enkhuizen', '0388');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Haarlem', '0392');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Haarlemmerliede en Spaarnwoude', '0393');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Haarlemmermeer', '0394');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Harenkarspel', '0395');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Heemskerk', '0396');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Heemstede', '0397');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Heerhugowaard', '0398');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Heiloo', '0399');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Den Helder', '0400');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hilversum', '0402');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hoorn', '0405');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Huizen', '0406');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Niedorp', '0412');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Landsmeer', '0415');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Langedijk', '0416');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Laren', '0417');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Medemblik', '0420');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Muiden', '0424');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Naarden', '0425');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oostzaan', '0431');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Opmeer', '0432');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ouder-Amstel', '0437');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Purmerend', '0439');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Schagen', '0441');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Texel', '0448');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Uitgeest', '0450');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Uithoorn', '0451');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Velsen', '0453');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Weesp', '0457');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Schermer', '0458');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wervershoof', '0459');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wieringen', '0462');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wieringermeer', '0463');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zandvoort', '0473');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zijpe', '0476');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zeevang', '0478');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zaanstad', '0479');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Alblasserdam', '0482');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Alkemade', '0483');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Alphen aan den Rijn', '0484');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Barendrecht', '0489');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bergambacht', '0491');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bodegraven', '0497');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Drechterland', '0498');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Boskoop', '0499');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Brielle', '0501');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Capelle aan den IJssel', '0502');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Delft', '0503');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Dirksland', '0504');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Dordrecht', '0505');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Goedereede', '0511');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Gorinchem', '0512');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Gouda', '0513');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'''s-Gravenhage', '0518');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hardinxveld-Giessendam', '0523');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hellevoetsluis', '0530');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hendrik-Ido-Ambacht', '0531');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Stede Broec', '0532');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hillegom', '0534');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Katwijk', '0537');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Krimpen aan den IJssel', '0542');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Leerdam', '0545');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Leiden', '0546');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Leiderdorp', '0547');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Lisse', '0553');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Maassluis', '0556');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Middelharnis', '0559');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Moordrecht', '0563');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nieuwerkerk aan den IJssel', '0567');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bernisse', '0568');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nieuwkoop', '0569');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nieuw-Lekkerland', '0571');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Noordwijk', '0575');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Noordwijkerhout', '0576');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oegstgeest', '0579');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oostflakkee', '0580');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oud-Beijerland', '0584');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Binnenmaas', '0585');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Korendijk', '0588');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oudewater', '0589');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Papendrecht', '0590');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Reeuwijk', '0595');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ridderkerk', '0597');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Rotterdam', '0599');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Rozenburg', '0600');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Rijswijk', '0603');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Schiedam', '0606');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Schoonhoven', '0608');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Sliedrecht', '0610');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Cromstrijen', '0611');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Spijkenisse', '0612');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Albrandswaard', '0613');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Westvoorne', '0614');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Strijen', '0617');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Vianen', '0620');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Vlaardingen', '0622');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Vlist', '0623');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Voorschoten', '0626');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Waddinxveen', '0627');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wassenaar', '0629');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Woerden', '0632');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zoetermeer', '0637');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zoeterwoude', '0638');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zwijndrecht', '0642');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nederlek', '0643');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ouderkerk', '0644');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Jacobswoude', '0645');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Gaasterl?n-Sleat', '0653');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Borsele', '0654');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Goes', '0664');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'West Maas en Waal', '0668');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hulst', '0677');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Kapelle', '0678');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wymbritseradiel', '0683');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Middelburg', '0687');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Giessenlanden', '0689');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Graafstroom', '0693');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Liesveld', '0694');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Reimerswaal', '0703');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zederik', '0707');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'W?nseradiel', '0710');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Terneuzen', '0715');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Tholen', '0716');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Veere', '0717');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Vlissingen', '0718');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Lingewaal', '0733');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'De Ronde Venen', '0736');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Tytsjerksteradiel', '0737');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Aalburg', '0738');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Asten', '0743');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Baarle-Nassau', '0744');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bergen op Zoom', '0748');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Best', '0753');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Boekel', '0755');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Boxmeer', '0756');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Boxtel', '0757');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Breda', '0758');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Deurne', '0762');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Pekela', '0765');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Dongen', '0766');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Eersel', '0770');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Eindhoven', '0772');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Etten-Leur', '0777');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Geertruidenberg', '0779');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Gilze en Rijen', '0784');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Goirle', '0785');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Grave', '0786');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Haaren', '0788');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Helmond', '0794');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'''s-Hertogenbosch', '0796');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Heusden', '0797');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hilvarenbeek', '0798');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Lith', '0808');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Loon op Zand', '0809');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Mill en Sint Hubert', '0815');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nuenen, Gerwen en Nederwetten', '0820');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oirschot', '0823');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oisterwijk', '0824');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oosterhout', '0826');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oss', '0828');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Rucphen', '0840');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Schijndel', '0844');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Sint-Michielsgestel', '0845');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Sint-Oedenrode', '0846');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Someren', '0847');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Son en Breugel', '0848');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Steenbergen', '0851');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Waterland', '0852');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Tilburg', '0855');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Uden', '0856');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Valkenswaard', '0858');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Veghel', '0860');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Veldhoven', '0861');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Vught', '0865');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Waalre', '0866');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Waalwijk', '0867');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Werkendam', '0870');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Woensdrecht', '0873');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Woudrichem', '0874');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zundert', '0879');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wormerland', '0880');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Onderbanken', '0881');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Landgraaf', '0882');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Arcen en Velden', '0885');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Beek', '0888');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Beesel', '0889');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bergen (L.)', '0893');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Brunssum', '0899');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Eijsden', '0905');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Gennep', '0907');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Heerlen', '0917');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Helden', '0918');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Kerkrade', '0928');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Kessel', '0929');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Maasbree', '0934');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Maastricht', '0935');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Margraten', '0936');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Meerssen', '0938');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Meijel', '0941');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Mook en Middelaar', '0944');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nederweert', '0946');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Nuth', '0951');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Roermond', '0957');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Schinnen', '0962');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Sevenum', '0964');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Simpelveld', '0965');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Stein', '0971');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Vaals', '0981');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Venlo', '0983');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Venray', '0984');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Voerendaal', '0986');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Weert', '0988');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Meerlo-Wanssum', '0993');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Valkenburg aan de Geul', '0994');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Lelystad', '0995');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Horst aan de Maas', '1507');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oude IJsselstreek', '1509');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Teylingen', '1525');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Utrechtse Heuvelrug', '1581');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Oost Gelre', '1586');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Koggenland', '1598');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Lansingerland', '1621');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Leudal', '1640');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Maasgouw', '1641');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Eemsmond', '1651');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Gemert-Bakel', '1652');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Halderberge', '1655');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Heeze-Leende', '1658');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Laarbeek', '1659');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Reiderland', '1661');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'De Marne', '1663');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zevenhuizen-Moerkapelle', '1666');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Reusel-De Mierden', '1667');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Roerdalen', '1669');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Maasdonk', '1671');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Rijnwoude', '1672');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Roosendaal', '1674');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Schouwen-Duiveland', '1676');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Aa en Hunze', '1680');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Borger-Odoorn', '1681');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Cuijk', '1684');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Landerd', '1685');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'De Wolden', '1690');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Noord-Beveland', '1695');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Wijdemeren', '1696');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Noordenveld', '1699');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Twenterand', '1700');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Westerveld', '1701');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Sint Anthonis', '1702');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Lingewaard', '1705');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Cranendonck', '1706');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Steenwijkerland', '1708');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Moerdijk', '1709');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Echt-Susteren', '1711');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Sluis', '1714');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Drimmelen', '1719');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bernheze', '1721');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Ferwerderadiel', '1722');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Alphen-Chaam', '1723');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bergeijk', '1724');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bladel', '1728');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Gulpen-Wittem', '1729');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Tynaarlo', '1730');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Midden-Drenthe', '1731');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Overbetuwe', '1734');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Hof van Twente', '1735');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Neder-Betuwe', '1740');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Rijssen-Holten', '1742');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Geldrop-Mierlo', '1771');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Olst-Wijhe', '1773');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Dinkelland', '1774');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Westland', '1783');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Midden-Delfland', '1842');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Berkelland', '1859');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Bronckhorst', '1876');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Sittard-Geleen', '1883');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Zwartewaterland', '1896');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Leidschendam-Voorburg', '1916');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Pijnacker-Nootdorp', '1926');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Montferland', '1955');
insert into planeigenaar (id,naam, code) values (planeigenaar_id_seq.NEXTVAL,'Menterwolde', '1987');
